# Generated by Django 6.0.1 on 2026-01-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_saleitem_cost_alter_sale_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_count', models.IntegerField(default=0)),
                ('best_seller_by_quantity', models.CharField(blank=True, max_length=200)),
                ('best_seller_quantity', models.IntegerField(default=0)),
                ('best_seller_by_profit', models.CharField(blank=True, max_length=200)),
                ('best_seller_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('products_sold', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Summaries',
                'ordering': ['-date'],
            },
        ),
    ]
