# Generated by Django 6.0.2 on 2026-02-08 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_periodtotals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The staff member who processed this sale (nullable).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='low_stock_limit',
            field=models.IntegerField(default=5, help_text='Products with quantity below this are flagged as low stock.'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Default profit margin percentage for new products.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='theme',
            field=models.CharField(default='light', help_text="UI theme: 'light' or 'dark'.", max_length=10),
        ),
    ]
