# Generated by Django 6.0.2 on 2026-02-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_sale_user_alter_storesettings_low_stock_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='original_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before surcharge. Mirrors total_debt when surcharge is 0%.', max_digits=10),
        ),
        migrations.AddField(
            model_name='debtor',
            name='surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Peso value of the surcharge (original_total × surcharge_percent / 100).', max_digits=10),
        ),
        migrations.AddField(
            model_name='debtor',
            name='surcharge_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Surcharge rate (%) applied at the time this debt was created.', max_digits=5),
        ),
        migrations.AddField(
            model_name='debtoritem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='debt_surcharge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage surcharge added on top of the subtotal when recording a new debt.', max_digits=5),
        ),
    ]
