# Generated by Django 6.0.2 on 2026-02-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_debtor_original_total_debtor_surcharge_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='change_history',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of settings change records. Shared across all devices.'),
        ),
    ]
