# Generated by Django 6.0.2 on 2026-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_sale_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_date', models.DateField(db_index=True)),
                ('items_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payment History',
                'ordering': ['-paid_date'],
                'indexes': [models.Index(fields=['paid_date'], name='store_payme_paid_da_fdd2d2_idx'), models.Index(fields=['customer_name'], name='store_payme_custome_d9eb4c_idx')],
            },
        ),
    ]
