# Generated by Django 6.0.1 on 2026-01-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_storesettings_sound_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('credit-paid', 'Credit Paid')], max_length=20),
        ),
    ]
