# Generated by Django 6.0.1 on 2026-01-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_dailysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('yesterday', 'Yesterday'), ('last_week', 'Last Week'), ('last_month', 'Last Month'), ('last_year', 'Last Year')], max_length=20, unique=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_count', models.IntegerField(default=0)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Period Totals',
            },
        ),
    ]
