# Generated by Django 6.0.2 on 2026-03-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_fix_paymenthistory_all_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='date_borrowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='original_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='surcharge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
